---
remotes:
  vendor: https://github.com/mxcl/homebrew
  primary: git@github.com:destructuring/homebrew
  secondary: git@bitbucket.org:destructuring/homebrew
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
